version: '2'
services:
  proxy_mongo:
    image: mongo
    ports:
      - 27017
    command: mongod --directoryperdb

  echo:
    image: solsson/http-echo
    ports: 
      - 80

  sails_proxy:
    depends_on:
      - proxy_mongo
      - echo
    image: twhtanghk/sails_proxy
    ports:
      - 1337
    env_file:
      - ./.env

  oauth2_code:
    depends_on:
      - sails_proxy
    image: twhtanghk/oauth2_code
    ports:
      - 1337:1337
    env_file:
      - ./.env
